### ISSUE TITLE
Updating blog to GitHubPages Jekyll 3 before 1.5.2016

### ISSUE THREAD

**Issue by Rinorragi** [solita/solita.github.com#152]
Highlighter should be changed to "rouge" and markdown to "kramdown". This seems to have negative effect on our vagrant machine. Please communicate without using here tags while fixing this. 

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by jkumara** [comment]
I'll start looking into this

**Comment by jtiala** [comment]
Done years ago.
