### ISSUE TITLE
Post Meta overflowing issues

### ISSUE THREAD

**Issue by thevangelist** [solita/solita.github.com#206]
Author information is overflowing on top of content. See screen below.

![screen shot 2017-01-04 at 19 05 13](https://cloud.githubusercontent.com/assets/3482617/21651325/e102c842-d2b0-11e6-919b-13e766b1d35b.png)

Suggestion: use flexbox to lay out each post.

PS. Greetings from a fellow blogger: https://dev.solteq.com (You inspired us!)

**Comment by Kauko** [comment]
Thanks for the report and good luck with your blog! :)

<img width="549" alt="screen shot 2017-02-09 at 12 04 55" src="https://cloud.githubusercontent.com/assets/804522/22778576/1bc67d7c-eec0-11e6-985e-f1b4efb2976f.png">
