### ISSUE TITLE
Add tw:via="SolitaOy" to tweet button

### ISSUE THREAD

**Issue by Darep** [solita/solita.github.com#28]
> jarnopeltoniemi commented 2 days ago 
> Ei suurta merkitystä, mutta laittaisko tuohon tweet-nappiin tw:via="solitaoy". Tulisipa mainittua Solita jakaessa.

**Comment by Kauko** [comment]
Just meinasin että vois avata issuen siitä, että blogiin pitäis saada tweettausnappi, mut ilmeisesti sellainen on jo? Missä, en löydä? :o

**Comment by Darep** [comment]
Mä laitoin ainakin aikanaan sinne AddThis:n ja tweet-nappi oli jokasen
yksittäisen postauksen perässä. En tiiä onko ennää :D
